class GamePhysics:
    ROUND_TIME = 30
    FRAMES_PER_SECONDS = 60
    DELAY_SECOND = 1.0 / FRAMES_PER_SECONDS
    TANK_SPEED = 8.0
    TANK_QUARTER_ROTATION_DURATION = 0.2

    KILL_POINTS = 1000
    ITEM_POINTS = 300

    WINDOW_WIDTH = 1400
    WINDOW_HEIGHT = 850

