package model.game.elements;

public enum LevelElementType {
    BLOCK, BLOCK_METAL, BLOCK_WOOD, BLOCK_STONE, TANK, TANK_1, TANK_2 , TANK_3, TANK_4, BULLETMAINWEAPON, BULLETSECONDARYWEAPON, ITEM, DISPLAY
}
