package model.service;

public enum MessageType {
    LOGIN, CONNECT,JOIN, CHAT_MSG, GET_LOBBIES , CLOSE_LOBBY, LEAVE_LOBBY, JOINED_PLAYER, REGISTER_LOBBY, START_GAME, RDY_STATUS, TANK_MOVE,
    FIRE_MAIN, REMOVE_LOBBY, WHAT_IS_YOUR_STATUS

}
